### ISSUE TITLE
Incorrect position check in IsUtf8?

### ISSUE THREAD

**Issue by pedasmith** [gro-ove/actools#11]
It looks like a lot of the UTF8 checker code on GitHub is all copied with what appears to be the same issue: if the utf8 multi-byte sequence is at the end of the buffer, it's incorrectly marked as invalid. AFAICT, all of the checks for position >= length -2 (or whatever) should be position > length-2.

**Comment by gro-ove** [comment]
Oh, great catch! Doing God's work here with those issues, thank you.

**Comment by pedasmith** [comment]
FYI: I've just created a near drop-in IsUtf8 [replacement](https://github.com/pedasmith/NetworkParser/tree/master/NetworkParsers/NetworkParsers); that project includes a bunch of unit tests.
