### ISSUE TITLE
Add Kosovo as a Nationality Option

### ISSUE THREAD

**Issue by JoshButler** [gro-ove/actools#116]
Dear Content Manager Development Team,

I am a dedicated user of Content Manager and deeply appreciate the excellent functionality it offers for enhancing the Assetto Corsa experience. One of the features I particularly value is the ability to create an online username and select a nationality. However, I was dismayed to discover that Kosovo is not listed as an available nationality option.

This omission is not just a minor oversight; it is a significant issue for me and many others who are proud of our Kosovar heritage. Kosovo has a unique and rich history, marked by struggle and resilience. Recognizing Kosovo as a nation in Content Manager is not just about adding a flag; it is about acknowledging the identity and pride of a people who have fought hard for their place in the world.

The inclusion of Kosovo as a nationality option would allow me and others to represent our country with pride as we race against competitors from around the globe. It is essential for fostering an inclusive and respectful community within the game.

I urge you to address this issue promptly and add Kosovo to the list of selectable nationalities in Content Manager. Thank you for your attention to this matter and for continuing to improve this fantastic tool.

**Comment by barf** [comment]
Kia ora from New Zealand!

The issue may be that .xk is not listed in [ISO 3166](https://www.iso.org/iso-3166-country-codes.html) which most operating systems and applications derive their country list from? SAP for example also omits .xk and SAP is a big European company...

There are no country lists or flags icons in this repo at all that I can find, however the CSP is distributed with an atlas texture that omits this flag, despite including Antarctica... perhaps more concerning is binaries are also distributed in CSP but without the source here, such as the mumble client... so I cannot fix issues with it's TLS 1.0 requirement... Microsoft (and ISO) may be a better avenue for reporting this I think.

**Comment by barf** [comment]
Did some digging and it's in a separate repo, explaining why I couldn't find it here, have submitted a Pull request if any maintainer would be so kind as to merge we can close this.

**Comment by JoshButler** [comment]
Kia ora!

Thank you so much for taking the time to look into this issue and for identifying a solution. Your efforts are greatly appreciated! It's reassuring to know that the fix is in progress, and I look forward to seeing Kosovo proudly represented in Content Manager.

You've done a great service, and you can sleep soundly knowing you've helped bring recognition to a nation that holds deep meaning for many of us. Keep up the excellent work, and thank you again for your dedication and support.

Best regards

**Comment by barf** [comment]
You're welcome! But I should note the pull requests here are all gathering dust, including for crash fixes, I don't mind trying but it may just be ignored like the others.

I don't actually know much about the whole conflict but there is a saying in motorsport: take it to the track! All the best!
