### ISSUE TITLE
cannot launch game through CM, it always show Race Cancelled 

### ISSUE THREAD

**Issue by RoninSun** [gro-ove/actools#122]
here is the detailed log file
https://drive.google.com/file/d/1V_dbvibBQOiaoqMaK_FlGgsmmPhEeFBL/view?usp=sharing

**Comment by Marocco2** [comment]
What was the issue?

**Comment by RoninSun** [comment]
Hi the issue has been fixed by deleting all the files and reinstalling. I
think there could be issue on installing CSP but after reinstalling
everything, it works now

Thanks,
Lingyu
