### ISSUE TITLE
CM showroom not reading BC7 dds textures.

### ISSUE THREAD

**Issue by IRBrainiac** [gro-ove/actools#125]
I have started using BC7 compression on some of my textures but I cant see them in CM showroom.They do show in the other showroom and ingame.
I can see PSDs in CM showroom if using skin editing mode.
CSP ver. 0.2.3
CM ver. 0.8.2727.39678 (x86)

thank you very much

**Comment by CheesyManiac** [comment]
Update to [v0.8.2731.39678](https://github.com/gro-ove/actools/releases/tag/v0.8.2731.39678)

**Comment by IRBrainiac** [comment]
Thank you very much...that worked.
