### ISSUE TITLE
Content Manager won't open

### ISSUE THREAD

**Issue by jocxfin** [gro-ove/actools#13]
![image](https://user-images.githubusercontent.com/19174728/55294708-fac47d80-540d-11e9-98f9-6f58477f193a.png)

I'm getting this error. Tried to rename the file to have "safe" and "local" in its name but that didn't help either. Any idea what's the problem.
My pc specs:
i9-9900k
rtx 2080
assetto corsa is installed in one of the ssds.

**Comment by gro-ove** [comment]
Oh whoa, very sorry about it, will fix asap. How could I forget about this part.

**Comment by jocxfin** [comment]
Thanks! Could you attach the fixed .exe file in this thread after you've finished fixing the issue? 

ps. thanks for the fast reply

**Comment by gro-ove** [comment]
That one should work, I believe.
https://github.com/gro-ove/actools/releases/tag/v0.8.1976.36095

**Comment by jocxfin** [comment]
Thanks! That works!
