### ISSUE TITLE
'Details ID' always appended to the end of server title in server_cfg.ini

### ISSUE THREAD

**Issue by dabinn** [gro-ove/actools#6]
After saving AC server setting with Content Manager, the 'Details IDs' always appended to the end of server title in server_cfg.ini. No mater which setting was seleted ('Via ID in name' or 'Via AC Server Wrapper'). Even unchecked the 'Provide extra details about the server' option, 'Details ID' still used.
(version: 0.8.1869.35097 (x86))
![image](https://user-images.githubusercontent.com/21699064/50377372-1a9e1580-0657-11e9-8be5-73efce500d0b.png)

**Comment by gro-ove** [comment]
Thank you, will fix!
