### ISSUE TITLE
CSP Causing Missing Car Textures

### ISSUE THREAD

**Issue by anjoo91** [gro-ove/actools#74]
Hi, 

Everytime I try to use CM to install CSP - regardless of version, I get this issue where the vehicles do not show up - screenshot below:
![image](https://user-images.githubusercontent.com/120999267/208340130-88a0ccdb-0a91-4c80-bc01-0a5b3f07e334.png)

I've isolated the issue to CSP after doing a clean reinstall and launching via CM with and without CSP installed. 

Any ideas why this keeps happening?

**Comment by Marocco2** [comment]
This is not a CSP troubleshooting section.
Head over to CSP discord server or Shuto discord to receive support
