### ISSUE TITLE
Extra Live Service not adding new sites (ie: lowfuelmotorsport)

### ISSUE THREAD

**Issue by Alf3rez** [gro-ove/actools#94]
Hi, after trying to add Low Fuel Motorsport as an extra Live Service, the app doesn't do it right, even if I put the url right ([https://lowfuelmotorsport.com](https://lowfuelmotorsport.com)) and it gives me back the right title (_Low Fuel Motorsport | Biggest platform for competitive SimRacing in ACC and rF2_), or I use any other custom name, when I press "Ok" nothing happens, the window just closes and that's all.

Maybe is user error, but I couldn't find anything related to this that was different to press Add, paste and press Ok.

Thank you for all your work!

**Comment by egranto** [comment]
still present i also test 
https://blckbox.net/

**Comment by Alf3rez** [comment]
Now is included in the last version, so it's ok
